### ISSUE TITLE
hackage readme corrupted

### ISSUE THREAD

**Issue by ghorn** [ndmitchell/cmdargs#25]
Looks like the htmls are leaking http://hackage.haskell.org/package/cmdargs#readme

**Comment by ndmitchell** [comment]
The README used to be HTML. I converted enough of it to Markdown so that Github was happy, but obviously Hackage has a different set of allowed HTML bits in its Markdown (quite reasonably, as the bits I was doing are entirely nonstandard). I guess I need to finish the conversion to Markdown properly - thanks for pointing it out.

**Comment by ndmitchell** [comment]
All converted to complete Markdown now.
